services:
  postgres:
    image: postgres:15.8-alpine3.19
    mem_limit: 256m
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=rails_template
      - POSTGRES_PASSWORD=rails_template_pg_passwd

volumes:
  postgresql: